"""empty message

Revision ID: 2038daa9c98f
Revises: 
Create Date: 2019-02-20 00:21:02.336444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2038daa9c98f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('sno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('DATE', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('users',
    sa.Column('sno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('mobile_no', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('feedback')
    # ### end Alembic commands ###
