"""empty message

Revision ID: 27e480710146
Revises: 2038daa9c98f
Create Date: 2019-02-20 00:27:26.214499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e480710146'
down_revision = '2038daa9c98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('feedback', sa.Column('mobile_no', sa.String(length=10), nullable=True))
    op.add_column('feedback', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'name')
    op.drop_column('feedback', 'mobile_no')
    op.drop_column('feedback', 'email')
    # ### end Alembic commands ###
